In [8]:
import random

import numpy as np

z = np.zeros((5, 5))
print(z)
type(z)
a = [random.randint(0, 5) for _ in range(10)]
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[4, 3, 0, 5, 2, 0, 2, 5, 5, 0]


In [12]:
def random_value_arr(arr, num, inf, sup):
    c_arr = np.copy(arr)
    assert type(arr) == np.ndarray
    a = [random.randint(0, arr.shape[0] - 1) for i in range(num)]
    b = [random.randint(0, arr.shape[1] - 1) for i in range(num)]
    c = zip(a, b)
    for i in c:
        c_arr[i] = random.randint(inf, sup)
    return c_arr



In [14]:
z2 = random_value_arr(z, 10, 0, 8)
print(z2)

[[0. 0. 0. 2. 3.]
 [8. 2. 0. 6. 3.]
 [0. 6. 1. 1. 2.]
 [4. 1. 5. 0. 4.]
 [7. 5. 3. 1. 7.]]


In [16]:
a = np.matrix([[1, 2], [3, 4]])
print(a)



[[1 2]
 [3 4]]


In [18]:
b = a @ a
print(b)
print(np.dot(a, a))

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [22]:

print(np.multiply(a, a))

[[ 1  4]
 [ 9 16]]


In [23]:
print(np.prod(a))

24


In [24]:
z2
z2 + 3

array([[ 3.,  3.,  3.,  5.,  6.],
       [11.,  5.,  3.,  9.,  6.],
       [ 3.,  9.,  4.,  4.,  5.],
       [ 7.,  4.,  8.,  3.,  7.],
       [10.,  8.,  6.,  4., 10.]])

In [27]:
d = np.ones((3, 3))
e = np.array([-2, 2, 7])
d + e

array([[-1.,  3.,  8.],
       [-1.,  3.,  8.],
       [-1.,  3.,  8.]])

In [28]:
np.sum(z2)

71.0

In [29]:
np.cumsum(z2)

array([ 0.,  0.,  0.,  2.,  5., 13., 15., 15., 21., 24., 24., 30., 31.,
       32., 34., 38., 39., 44., 44., 48., 55., 60., 63., 64., 71.])

In [30]:
np.cumsum(z2, axis=0)
np.cumsum(z2, axis=1)

array([[ 0.,  0.,  0.,  2.,  5.],
       [ 8., 10., 10., 16., 19.],
       [ 0.,  6.,  7.,  8., 10.],
       [ 4.,  5., 10., 10., 14.],
       [ 7., 12., 15., 16., 23.]])

In [31]:
z2 / z2

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8236\1941571896.py:1: RuntimeWarning: invalid value encountered in divide
  z2/z2


array([[nan, nan, nan,  1.,  1.],
       [ 1.,  1., nan,  1.,  1.],
       [nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., nan,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [32]:
np.subtract(z2, z2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.divide(z2, 3)

array([[0.        , 0.        , 0.        , 0.66666667, 1.        ],
       [2.66666667, 0.66666667, 0.        , 2.        , 1.        ],
       [0.        , 2.        , 0.33333333, 0.33333333, 0.66666667],
       [1.33333333, 0.33333333, 1.66666667, 0.        , 1.33333333],
       [2.33333333, 1.66666667, 1.        , 0.33333333, 2.33333333]])

In [37]:
np.floor_divide(z2, 3)

array([[0., 0., 0., 0., 1.],
       [2., 0., 0., 2., 1.],
       [0., 2., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [2., 1., 1., 0., 2.]])

In [40]:
np.math.sqrt(7)

2.6457513110645907

In [41]:
np.math.nan

nan

In [42]:
np.math.inf

inf

In [43]:
z3 = np.random.uniform(0, 1, (5, 5))
z3

array([[0.4897077 , 0.67288797, 0.23848643, 0.87250299, 0.06680336],
       [0.01756695, 0.5246059 , 0.60202179, 0.16473915, 0.17389118],
       [0.07864191, 0.57994397, 0.95787381, 0.51391318, 0.08428085],
       [0.6055084 , 0.21308223, 0.11335077, 0.90374862, 0.98138986],
       [0.63970151, 0.79429104, 0.09227612, 0.23233652, 0.10074344]])

In [44]:
z4 = np.random.standard_normal((5, 5))
z4

array([[-1.79694463,  1.10690933,  0.15910229, -0.08622424,  1.61228529],
       [-1.0279809 , -1.40052589, -1.32687723, -0.16002124, -0.5135852 ],
       [-0.97100973,  1.50522409,  1.09290014,  0.5127918 , -0.22562469],
       [-2.85430005,  0.35483017,  1.15191185,  0.80768609, -0.13987003],
       [-0.48273223,  0.90086037,  0.25086505,  0.16981847,  1.15067946]])

In [45]:
rand = np.arange(1, 10, 2)
rand

array([1, 3, 5, 7, 9])

In [46]:
rand2 = np.linspace(1, 10, 3)
rand2

array([ 1. ,  5.5, 10. ])

In [50]:
my_mask = z2 > 7
z2[my_mask]

array([8.])

In [51]:
my_mask

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [53]:
np.where(z2[my_mask])

(array([0], dtype=int64),)

In [54]:
np.unique(z2)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [56]:
aa = np.array([1, 2, 3, 5, 7, 8, 5, 4, 2])
bb = np.array([1, 2, 3, 4, 7, 6, 5, 2, 38, 36])
np.union1d(aa, bb)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 36, 38])

In [57]:
np.intersect1d(aa, bb)

array([1, 2, 3, 4, 5, 7])

In [58]:
np.mean(z2)


2.0

In [59]:
np.median(z2)

2.0

In [60]:
np.std(z2)

2.5088642848906755

In [61]:
aaa = np.array([])
aaa

array([], dtype=float64)

In [65]:
chandjomlei = np.array([1, 2, 5])
np.polyval(chandjomlei, 2)

13

In [66]:
der = np.polyder(chandjomlei)
der

array([2, 2])

In [67]:
intg = np.polyint(chandjomlei)
intg

array([0.33333333, 1.        , 5.        , 0.        ])