In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
brs = load_breast_cancer()
brs_df = pd.DataFrame(brs.data, columns=brs.feature_names)
brs_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [4]:
brs_df['target'] = brs.target
brs

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [5]:
brs.target_names

array(['malignant', 'benign'], dtype='<U9')

In [6]:
brs_df['target_names'] = ''
brs_df['target_names'][brs_df.target == 0] = brs.target_names[0]
brs_df['target_names'][brs_df.target == 1] = brs.target_names[1]
brs_df

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_13948\1563169771.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brs_df['target_names'][brs_df.target == 0] = brs.target_names[0]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_13948\1563169771.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  brs_df['target_names'][brs_df.target == 1] = brs.target_names[1]


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst perimeter  worst area  \
0                   0.07871  ...           184.60      2019.0   
1                   0.05667  ...           158.80      1956.0   
2                   0.05999  ...           152.50      1709.0   
3                   0.09744  ...            98.87       567.7   
4                   0.05883  ...           152.20      1575.0   
..                      ...  ...              ...         ...   
564                 0.05623  ...           166.10      2027.0   
565                 0.05533  ...           155.00      1731.0   
566                 0.05648  ...           126.70      1124.0   
567                 0.07016  ...           184.60      1821.0   
568                 0.05884  ...            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  \
0                  0.2654          0.4601                  0.11890       0   
1                  0.1860          0.2750                  0.08902       0   
2                  0.2430          0.3613                  0.08758       0   
3                  0.2575          0.6638                  0.17300       0   
4                  0.1625          0.2364                  0.07678       0   
..                    ...             ...                      ...     ...   
564                0.2216          0.2060                  0.07115       0   
565  

In [7]:
x = brs.data
y = brs.target

In [8]:
x

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [9]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import backend as K

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [11]:
lb_encoder = LabelEncoder()
lb_encoder.fit(brs_df.target_names)
labels = lb_encoder.transform(brs_df.target_names)
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [12]:
x_tr, x_ts, y_tr, y_ts = train_test_split(x, y, test_size=0.2, shuffle=True)

In [13]:
sc = StandardScaler()
x_tr = sc.fit_transform(x_tr)
x_ts = sc.transform(x_ts)
x_tr

array([[ 1.9201802 ,  0.93964435,  1.91433302, ...,  1.45039486,
         0.3636515 , -0.29189084],
       [-0.42152734, -1.66379749, -0.4720893 , ..., -0.49867711,
        -0.20507255,  0.56734933],
       [ 0.11274574,  0.47564198,  0.20780662, ...,  2.35609179,
         2.20754887,  2.31562375],
       ...,
       [-0.37321542,  0.02078252, -0.39846475, ..., -0.77828824,
         0.66664694, -0.35254309],
       [-0.70287327, -0.63522082, -0.72545644, ..., -0.6895421 ,
        -1.92744768, -0.56110169],
       [-0.37889917,  0.43907037, -0.40011   , ..., -0.89727494,
        -0.67009764, -0.13121559]])

In [14]:
NN = Sequential()
NN.add(Dense(1, activation='sigmoid', input_shape=(30,)))

In [15]:
NN.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [16]:
NN.fit(x_tr, y_tr, batch_size=50, epochs=150)

Epoch 1/150
10/10 [==============================] - 1s 2ms/step - loss: 1.7787 - accuracy: 0.1033
Epoch 2/150
10/10 [==============================] - 0s 4ms/step - loss: 1.6634 - accuracy: 0.1033
Epoch 3/150
10/10 [==============================] - 0s 4ms/step - loss: 1.5558 - accuracy: 0.1055
Epoch 4/150
10/10 [==============================] - 0s 3ms/step - loss: 1.4537 - accuracy: 0.1099
Epoch 5/150
10/10 [==============================] - 0s 3ms/step - loss: 1.3521 - accuracy: 0.1231
Epoch 6/150
10/10 [==============================] - 0s 6ms/step - loss: 1.2587 - accuracy: 0.1473
Epoch 7/150
10/10 [==============================] - 0s 4ms/step - loss: 1.1739 - accuracy: 0.1604
Epoch 8/150
10/10 [==============================] - 0s 3ms/step - loss: 1.0906 - accuracy: 0.1912
Epoch 9/150
10/10 [==============================] - 0s 4ms/step - loss: 1.0139 - accuracy: 0.2352
Epoch 10/150
10/10 [==============================] - 0s 3ms/step - loss: 0.9435 - accuracy: 0.2703
Epoch 11/

In [17]:
val_loss, val_acc = NN.evaluate(x_ts, y_ts)

4/4 [==============================] - 0s 3ms/step - loss: 0.1090 - accuracy: 0.9737


In [18]:
val_loss

0.1090112030506134

In [19]:
val_acc

0.9736841917037964

In [20]:
NN2 = Sequential()
NN2.add(Dense(5, activation='relu', input_shape=(30,)))
NN2.add(Dense(1, activation='sigmoid'))
NN2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
NN2.fit(x_tr, y_tr, batch_size=50, epochs=150)

Epoch 1/150
10/10 [==============================] - 1s 1ms/step - loss: 0.9604 - accuracy: 0.4857
Epoch 2/150
10/10 [==============================] - 0s 3ms/step - loss: 0.8407 - accuracy: 0.5451
Epoch 3/150
10/10 [==============================] - 0s 10ms/step - loss: 0.7428 - accuracy: 0.6022
Epoch 4/150
10/10 [==============================] - 0s 7ms/step - loss: 0.6577 - accuracy: 0.6374
Epoch 5/150
10/10 [==============================] - 0s 4ms/step - loss: 0.5841 - accuracy: 0.6813
Epoch 6/150
10/10 [==============================] - 0s 5ms/step - loss: 0.5251 - accuracy: 0.7143
Epoch 7/150
10/10 [==============================] - 0s 7ms/step - loss: 0.4813 - accuracy: 0.7429
Epoch 8/150
10/10 [==============================] - 0s 6ms/step - loss: 0.4417 - accuracy: 0.7758
Epoch 9/150
10/10 [==============================] - 0s 2ms/step - loss: 0.4085 - accuracy: 0.8066
Epoch 10/150
10/10 [==============================] - 0s 2ms/step - loss: 0.3802 - accuracy: 0.8330
Epoch 11

In [21]:
val_loss2, val_acc2 = NN2.evaluate(x_ts, y_ts)

4/4 [==============================] - 0s 0s/step - loss: 0.0900 - accuracy: 0.9737


In [22]:
val_loss2

0.0899614691734314

In [23]:
val_acc2

0.9736841917037964

In [24]:
#import tensorflow.python.keras.layers

In [25]:
from sklearn.datasets import load_iris

In [26]:
iris = load_iris()

In [27]:
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [28]:
iris_df['target'] = iris.target
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [29]:
x_ir = iris.data
x_ir

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [30]:
y_ir = iris.target
y_ir

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [31]:
x_ = x_ir.copy()
y_ = y_ir.copy()

In [32]:
for i in range(len(x_[0])):
    m = np.min(x_[:, i])
    x_[:, i] += -m
    l = 0
    for j in x_[:, i]:
        l += j ** 2
    l = l ** (1 / 2)
    x_[:, i] /= l


In [33]:
x_

array([[0.03732251, 0.10714286, 0.00998345, 0.00611018],
       [0.02799188, 0.07142857, 0.00998345, 0.00611018],
       [0.01866126, 0.08571429, 0.00748759, 0.00611018],
       [0.01399594, 0.07857143, 0.01247931, 0.00611018],
       [0.0326572 , 0.11428571, 0.00998345, 0.00611018],
       [0.05131845, 0.13571429, 0.01747103, 0.01833055],
       [0.01399594, 0.1       , 0.00998345, 0.01222036],
       [0.0326572 , 0.1       , 0.01247931, 0.00611018],
       [0.00466531, 0.06428571, 0.00998345, 0.00611018],
       [0.02799188, 0.07857143, 0.01247931, 0.        ],
       [0.05131845, 0.12142857, 0.01247931, 0.00611018],
       [0.02332657, 0.1       , 0.01497517, 0.00611018],
       [0.02332657, 0.07142857, 0.00998345, 0.        ],
       [0.        , 0.07142857, 0.00249586, 0.        ],
       [0.06997971, 0.14285714, 0.00499172, 0.00611018],
       [0.06531439, 0.17142857, 0.01247931, 0.01833055],
       [0.05131845, 0.13571429, 0.00748759, 0.01833055],
       [0.03732251, 0.10714286,

In [34]:
x_tr_ir, x_ts_ir, y_tr_ir, y_ts_ir = train_test_split(x_, y_, test_size=0.2, shuffle=True)

In [36]:
NN_multy = Sequential()

In [46]:
NN_multy.add(Dense(15, activation='sigmoid',input_dim=4))
NN_multy.add(Dense(15, activation='relu', input_dim=4))
NN_multy.add(Dense(3,activation='softmax'))
NN_multy.add(Dense(1, activation='softmax'))

In [47]:
x_tr_ir

array([[0.03732251, 0.10714286, 0.00998345, 0.00611018],
       [0.08397565, 0.05714286, 0.07487586, 0.07332219],
       [0.06997971, 0.04285714, 0.07487586, 0.06721201],
       [0.03732251, 0.10714286, 0.00998345, 0.01222036],
       [0.0326572 , 0.07142857, 0.01497517, 0.00611018],
       [0.15862067, 0.12857143, 0.14226413, 0.12831383],
       [0.06064908, 0.07142857, 0.08735517, 0.08554255],
       [0.02332657, 0.1       , 0.01497517, 0.00611018],
       [0.07931034, 0.01428571, 0.07487586, 0.05499164],
       [0.09330628, 0.1       , 0.11480965, 0.1405342 ],
       [0.08864096, 0.06428571, 0.08236344, 0.07332219],
       [0.08864096, 0.1       , 0.10981792, 0.13442401],
       [0.0326572 , 0.        , 0.06239655, 0.05499164],
       [0.0326572 , 0.08571429, 0.00499172, 0.00611018],
       [0.06997971, 0.05      , 0.07237999, 0.06721201],
       [0.03732251, 0.12857143, 0.01247931, 0.01222036],
       [0.06531439, 0.07142857, 0.07986758, 0.06721201],
       [0.10263691, 0.08571429,

In [48]:
y_tr_ir

array([0, 1, 1, 0, 0, 2, 1, 0, 1, 2, 1, 2, 1, 0, 1, 0, 1, 2, 0, 1, 0, 0,
       1, 2, 2, 2, 0, 2, 2, 1, 0, 1, 2, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       2, 0, 0, 0, 2, 1, 2, 1, 2, 2, 0, 1, 1, 2, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 1, 2, 2,
       0, 1, 1, 0, 2, 2, 0, 1, 0, 2, 1, 1, 0, 2, 0, 1, 2, 0, 0, 1, 1, 1,
       2, 2, 2, 2, 1, 2, 0, 2, 2, 1])

In [49]:
NN_multy.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
NN_multy.fit(x_tr_ir, y_tr_ir, batch_size=15, epochs=100)

Epoch 1/100
8/8 [==============================] - 3s 2ms/step - loss: 0.6287 - accuracy: 0.3417
Epoch 2/100
8/8 [==============================] - 0s 4ms/step - loss: 0.6019 - accuracy: 0.3417
Epoch 3/100
8/8 [==============================] - 0s 4ms/step - loss: 0.5766 - accuracy: 0.3417
Epoch 4/100
8/8 [==============================] - 0s 2ms/step - loss: 0.5538 - accuracy: 0.3417
Epoch 5/100
8/8 [==============================] - 0s 4ms/step - loss: 0.5340 - accuracy: 0.3417
Epoch 6/100
8/8 [==============================] - 0s 2ms/step - loss: 0.5134 - accuracy: 0.3417
Epoch 7/100
8/8 [==============================] - 0s 3ms/step - loss: 0.4967 - accuracy: 0.3417
Epoch 8/100
8/8 [==============================] - 0s 4ms/step - loss: 0.4797 - accuracy: 0.3417
Epoch 9/100
8/8 [==============================] - 0s 4ms/step - loss: 0.4648 - accuracy: 0.3417
Epoch 10/100
8/8 [==============================] - 0s 3ms/step - loss: 0.4501 - accuracy: 0.3417
Epoch 11/100
8/8 [===========

In [50]:
NN_multy.evaluate(x_ts_ir,y_ts_ir)

1/1 [==============================] - 0s 223ms/step - loss: 0.2146 - accuracy: 0.3000


[0.21462233364582062, 0.30000001192092896]

In [53]:
NN_multy2=Sequential()

In [54]:
sc2=StandardScaler()

In [55]:
x2tr,x2ts,y2tr,y2ts=train_test_split(x_ir,y_ir,test_size=0.2,shuffle=True)

In [57]:
x2tr=sc2.fit_transform(x2tr)
x2ts=sc2.transform(x2ts)
x2tr

array([[ 0.23593016, -0.12317529,  0.6500984 ,  0.84372816],
       [ 1.12066825,  0.09743717,  1.11307649,  1.6483431 ],
       [-0.39602562,  0.97988703, -1.37543074, -1.30191167],
       [ 1.12066825,  0.5386621 ,  1.17094875,  1.24603563],
       [-0.90159025,  0.5386621 , -1.1439417 , -0.8996042 ],
       [-0.26963447, -0.78501269,  0.30286483,  0.17321572],
       [-1.78632834,  0.31804964, -1.37543074, -1.30191167],
       [-1.28076372, -0.12317529, -1.31755848, -1.16780918],
       [ 0.23593016, -0.78501269,  0.82371518,  0.57552318],
       [ 0.86788594, -0.12317529,  0.88158744,  1.11193314],
       [-1.02798141, -0.12317529, -1.20181396, -1.30191167],
       [ 0.48871247, -1.88807501,  0.47648162,  0.44142069],
       [ 2.38457982,  1.64172442,  1.74967136,  1.38013812],
       [ 1.12066825,  0.5386621 ,  1.17094875,  1.78244559],
       [ 0.61510363, -0.34378776,  1.11307649,  0.84372816],
       [-1.02798141,  1.20049949, -1.31755848, -1.30191167],
       [-0.01685215,  2.

In [58]:
x2ts

array([[-0.52241678,  0.75927457, -1.1439417 , -1.30191167],
       [ 0.61510363,  0.5386621 ,  1.34456553,  1.78244559],
       [ 0.86788594, -0.12317529,  1.05520423,  0.84372816],
       [ 0.23593016, -1.88807501,  0.76584292,  0.44142069],
       [ 0.36232132, -0.12317529,  0.70797066,  0.84372816],
       [-1.78632834, -0.34378776, -1.31755848, -1.30191167],
       [ 2.63736213,  1.64172442,  1.57605458,  1.11193314],
       [ 2.25818866, -0.12317529,  1.6917991 ,  1.24603563],
       [ 0.61510363,  0.5386621 ,  0.59222614,  0.57552318],
       [ 1.24705941, -0.56440022,  0.6500984 ,  0.30731821],
       [ 1.87901519, -0.34378776,  1.51818232,  0.84372816],
       [ 1.24705941,  0.31804964,  1.28669327,  1.51424061],
       [-1.28076372, -0.12317529, -1.31755848, -1.43601416],
       [ 0.48871247,  0.75927457,  0.99733197,  1.51424061],
       [-1.28076372,  0.75927457, -1.02819717, -1.30191167],
       [-0.52241678,  1.86233689, -1.37543074, -1.03370669],
       [-1.40715488,  0.

In [62]:
NN_multy2.add(Dense(15,activation='sigmoid',input_dim=4))
NN_multy2.add(Dense(15,activation='relu'))
NN_multy2.add(Dense(3,activation='relu'))
NN_multy2.add(Dense(1,activation='softmax'))

In [63]:
NN_multy2.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
NN_multy2.fit(x2tr,y2tr,batch_size=15,epochs=50)

Epoch 1/50
8/8 [==============================] - 2s 1ms/step - loss: 1.3359 - accuracy: 0.3500
Epoch 2/50
8/8 [==============================] - 0s 4ms/step - loss: 1.2016 - accuracy: 0.3500
Epoch 3/50
8/8 [==============================] - 0s 2ms/step - loss: 1.1093 - accuracy: 0.3500
Epoch 4/50
8/8 [==============================] - 0s 0s/step - loss: 1.0270 - accuracy: 0.3500
Epoch 5/50
8/8 [==============================] - 0s 2ms/step - loss: 0.9479 - accuracy: 0.3500
Epoch 6/50
8/8 [==============================] - 0s 2ms/step - loss: 0.8905 - accuracy: 0.3500
Epoch 7/50
8/8 [==============================] - 0s 2ms/step - loss: 0.8367 - accuracy: 0.3500
Epoch 8/50
8/8 [==============================] - 0s 2ms/step - loss: 0.7945 - accuracy: 0.3500
Epoch 9/50
8/8 [==============================] - 0s 2ms/step - loss: 0.7637 - accuracy: 0.3500
Epoch 10/50
8/8 [==============================] - 0s 930us/step - loss: 0.7364 - accuracy: 0.3500
Epoch 11/50
8/8 [=====================

In [64]:
NN_multy2.predict(x2tr)

4/4 [==============================] - 0s 2ms/step


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [65]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(hidden_layer_sizes=100,max_iter=50)
mlp.fit(x2tr,y2tr)

c:\users\admin\pycharmprojects\pythonproject5\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:679: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=100, max_iter=50)

In [66]:
mlp.score(x2ts,y2ts)

0.8

In [69]:
mlp2=MLPClassifier(hidden_layer_sizes=100,max_iter=50)
mlp2.fit(x_tr_ir,y_tr_ir)
mlp2.score(x_ts_ir,y_ts_ir)

c:\users\admin\pycharmprojects\pythonproject5\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:679: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


1.0

In [70]:
mlp2.score(x_tr_ir,y_tr_ir)

0.9

In [85]:
nn_mlp=Sequential()

In [116]:
nn_mlp.add(Dense(4,activation='relu',input_dim=4,input_shape=(4,)))
nn_mlp.add(Dense(16,activation='relu'))
nn_mlp.add(Dense(3,activation='softmax'))
#nn_mlp.add(Dense(1,activation='softmax'))


In [118]:
nn_mlp.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
nn_mlp.fit(x2tr,y2tr,batch_size=15,epochs=60)

Epoch 1/60
8/8 [==============================] - 2s 2ms/step - loss: 0.4649 - accuracy: 0.6917
Epoch 2/60
8/8 [==============================] - 0s 4ms/step - loss: 0.4632 - accuracy: 0.6917
Epoch 3/60
8/8 [==============================] - 0s 4ms/step - loss: 0.4624 - accuracy: 0.6917
Epoch 4/60
8/8 [==============================] - 0s 4ms/step - loss: 0.4613 - accuracy: 0.6917
Epoch 5/60
8/8 [==============================] - 0s 4ms/step - loss: 0.4603 - accuracy: 0.6917
Epoch 6/60
8/8 [==============================] - 0s 4ms/step - loss: 0.4601 - accuracy: 0.6917
Epoch 7/60
8/8 [==============================] - 0s 3ms/step - loss: 0.4592 - accuracy: 0.6917
Epoch 8/60
8/8 [==============================] - 0s 3ms/step - loss: 0.4587 - accuracy: 0.6917
Epoch 9/60
8/8 [==============================] - 0s 5ms/step - loss: 0.4583 - accuracy: 0.6917
Epoch 10/60
8/8 [==============================] - 0s 3ms/step - loss: 0.4577 - accuracy: 0.6917
Epoch 11/60
8/8 [======================

In [119]:
pr=nn_mlp.predict(x2tr)
pr

4/4 [==============================] - 0s 2ms/step


array([[1.30375760e-04, 3.49581838e-01, 6.50287747e-01],
       [1.30375760e-04, 3.49581838e-01, 6.50287747e-01],
       [9.91381824e-01, 8.61806888e-03, 7.08279160e-08],
       [1.30375760e-04, 3.49581838e-01, 6.50287747e-01],
       [9.91377711e-01, 8.62210616e-03, 7.08922272e-08],
       [3.85694066e-03, 8.86783838e-01, 1.09359242e-01],
       [9.91381347e-01, 8.61858577e-03, 7.08361227e-08],
       [9.91369307e-01, 8.63064639e-03, 7.10285946e-08],
       [2.64166360e-04, 4.65439975e-01, 5.34295857e-01],
       [1.30375760e-04, 3.49581838e-01, 6.50287747e-01],
       [9.91367042e-01, 8.63284897e-03, 7.10636598e-08],
       [4.47743246e-03, 8.99475455e-01, 9.60471258e-02],
       [1.30375760e-04, 3.49581838e-01, 6.50287747e-01],
       [1.30375760e-04, 3.49581838e-01, 6.50287747e-01],
       [1.30375760e-04, 3.49581838e-01, 6.50287747e-01],
       [9.91383135e-01, 8.61672871e-03, 7.08065286e-08],
       [9.91383433e-01, 8.61645490e-03, 7.08020949e-08],
       [1.30375760e-04, 3.49581

In [120]:
type(pr)

numpy.ndarray

In [121]:
pr.shape


(120, 3)

In [122]:
pr[0,:]

array([1.3037576e-04, 3.4958184e-01, 6.5028775e-01], dtype=float32)

In [123]:
def label(predict):
    labels_=[]
    for i in range(predict.shape[0]):
        row=predict[i,:]
        max=np.max(row)
        for j in range(len(row)):
            if predict[i,j]==max:
                labels_.append(j)
    return np.array(labels_)

In [124]:
lb=label(pr)
lb

array([2, 2, 0, 2, 0, 1, 0, 0, 2, 2, 0, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1,
       1, 0, 1, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 1, 2, 1, 1, 0, 1, 0, 0, 2,
       0, 1, 1, 0, 2, 0, 2, 2, 2, 2, 0, 1, 2, 0, 0, 0, 0, 1, 1, 2, 0, 1,
       1, 2, 0, 1, 0, 2, 2, 0, 1, 2, 2, 0, 2, 2, 0, 2, 0, 0, 1, 1, 0, 2,
       0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 2, 2, 0, 2, 0, 0, 1, 0, 1, 2, 2, 0,
       1, 2, 1, 1, 2, 2, 0, 0, 1, 2])

In [125]:
y2tr

array([2, 2, 0, 2, 0, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2,
       1, 0, 1, 1, 2, 2, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2,
       0, 1, 1, 0, 2, 0, 1, 2, 2, 2, 0, 1, 1, 0, 0, 0, 0, 1, 1, 2, 0, 1,
       1, 1, 0, 2, 0, 1, 2, 0, 1, 2, 2, 0, 1, 2, 0, 1, 0, 0, 1, 1, 0, 2,
       0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 2, 2, 0, 2, 0, 0, 1, 0, 1, 2, 2, 0,
       1, 2, 1, 1, 2, 2, 0, 0, 1, 2])

In [126]:
mask=lb==y2tr
np.sum(mask)/len(y2tr)

0.8916666666666667

In [127]:
nn_mlp.evaluate(x2ts,y2ts)

1/1 [==============================] - 0s 227ms/step - loss: 0.3885 - accuracy: 0.8667


[0.3885360360145569, 0.8666666746139526]