In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from tensorflow.keras.datasets.mnist import load_data

In [4]:
data = load_data()

In [5]:
(x_train, y_train), (x_test, y_test) = load_data()

In [6]:
x_train = x_train / 255

In [7]:
x_train.shape

(60000, 28, 28)

In [8]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [9]:
x_test = x_test / 255

In [10]:
x_test.shape

(10000, 28, 28)

In [11]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [12]:
x_train_c = x_train.reshape(60000, 28 * 28)

In [13]:
from sklearn.decomposition import PCA

In [14]:
pca = PCA(n_components=49)

In [15]:
x_train = pca.fit_transform(x_train_c)

In [16]:
x_train

array([[ 4.86010152e-01, -1.22617358e+00, -9.61335362e-02, ...,
         5.17922160e-01, -2.57200835e-01,  1.90618354e-01],
       [ 3.96752304e+00, -1.15630211e+00,  2.33858651e+00, ...,
        -1.02201061e+00, -6.79083136e-01,  5.02038079e-01],
       [-2.03331796e-01,  1.53793393e+00, -7.39253919e-01, ...,
         2.37490112e-02,  2.18428914e-01, -6.83674541e-01],
       ...,
       [-6.98248822e-01,  6.27757690e-01, -1.01024738e+00, ...,
        -1.47661853e-01, -3.50114668e-03,  3.56032846e-01],
       [ 5.12180675e-01, -2.19291624e-02,  2.01513205e+00, ...,
        -3.44102700e-03,  1.99526580e-02,  1.60667604e-01],
       [-6.80140990e-01, -9.69364794e-02,  2.18046625e+00, ...,
        -1.24481697e-01, -3.57470493e-01,  6.96672310e-01]])

In [17]:
x_test = pca.transform(x_test.reshape(10000, 28 * 28))

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential(
    [Dense(49, activation='relu', input_dim=49), Dense(10, activation='relu'), Dense(10, activation='softmax')])

In [20]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [50]:
from tensorflow.keras.callbacks import Callback
class loghistory(Callback):
    def on_train_begin(self, logs={}):
        self.losses = []
        self.acc = []
        self.weights1 = []
        self.weights2 = []

    def on_batch_end(self, batch ,logs={}):
        self.weights1.append(self.model.layer[1].get_weights())
        self.weights2.append(self.model.layer[2].get_weights())
        self.losses.append(logs.get('loss'))
        self.acc.append(logs.get('acc'))

In [69]:
from tensorflow.keras.callbacks import TensorBoard

In [70]:
import time
name=f'model{int(time.time())}'
tensor_board=TensorBoard(log_dir='C:\\Users\\ADMIN\\Desktop'+name,histogram_freq=1)

In [71]:
model.fit(x_train, y_train, batch_size=6000, epochs=150,callbacks=[tensor_board])

Epoch 1/150
10/10 [==============================] - 0s 30ms/step - loss: 0.0360 - accuracy: 0.9895
Epoch 2/150
10/10 [==============================] - 0s 17ms/step - loss: 0.0359 - accuracy: 0.9896
Epoch 3/150
10/10 [==============================] - 0s 19ms/step - loss: 0.0358 - accuracy: 0.9898
Epoch 4/150
10/10 [==============================] - 0s 16ms/step - loss: 0.0359 - accuracy: 0.9895
Epoch 5/150
10/10 [==============================] - 0s 15ms/step - loss: 0.0358 - accuracy: 0.9897
Epoch 6/150
10/10 [==============================] - 0s 17ms/step - loss: 0.0358 - accuracy: 0.9897
Epoch 7/150
10/10 [==============================] - 0s 14ms/step - loss: 0.0358 - accuracy: 0.9897
Epoch 8/150
10/10 [==============================] - 0s 15ms/step - loss: 0.0356 - accuracy: 0.9896
Epoch 9/150
10/10 [==============================] - 0s 17ms/step - loss: 0.0355 - accuracy: 0.9899
Epoch 10/150
10/10 [==============================] - 0s 21ms/step - loss: 0.0355 - accuracy: 0.9898

In [72]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.1226 - accuracy: 0.9728


[0.12258794158697128, 0.9728000164031982]

In [73]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(49, 49) dtype=float32, numpy=
 array([[ 0.5488598 , -0.49532345, -0.1925753 , ...,  0.20640631,
          0.41230944, -0.14865722],
        [-0.27706805,  0.25002897, -0.419819  , ..., -0.24312058,
         -0.39639348, -0.03478944],
        [-0.63690805, -0.16212176,  0.72813267, ...,  0.8573734 ,
         -0.16182518,  0.05193463],
        ...,
        [ 0.58024   ,  0.0223763 , -0.1561424 , ...,  0.07366052,
          0.74947834, -0.02042647],
        [ 0.06839023, -0.24281225, -0.6466002 , ...,  0.06912815,
          0.79956126,  0.05827476],
        [ 0.863233  ,  0.09757795, -0.08282947, ..., -0.2948319 ,
          0.3066127 , -0.07679905]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(49,) dtype=float32, numpy=
 array([ 2.86061503e-02, -2.53681690e-01,  2.73197651e-01,  2.25662798e-01,
         4.39091802e-01,  2.81417519e-01,  1.97148263e-01,  5.72479844e-01,
         9.57983732e-01,  1.11763412e-02, -6.99834168e-01,  8.30893219e-02

In [74]:
a = model.history.on_epoch_end

In [75]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 49)                2450      
                                                                 
 dense_1 (Dense)             (None, 10)                500       
                                                                 
 dense_2 (Dense)             (None, 10)                110       
                                                                 
Total params: 3060 (11.95 KB)
Trainable params: 3060 (11.95 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [76]:
model.layers[1].weights

[<tf.Variable 'dense_1/kernel:0' shape=(49, 10) dtype=float32, numpy=
 array([[-0.11523119,  0.74989414,  0.4867244 ,  0.10672428,  0.70857257,
         -0.15049213,  0.37308055,  0.2681915 , -0.42725733,  1.0608884 ],
        [ 0.72385377, -1.247887  ,  0.5411213 ,  0.16477267,  0.3617893 ,
         -0.2727737 ,  0.32806006, -0.01248247, -0.52733225,  0.3524414 ],
        [-0.30899724,  0.71733034,  0.01521957, -0.83580655, -0.11362807,
          0.16221197,  0.7763829 , -0.17205137,  0.5705083 ,  0.5456325 ],
        [-0.8464556 ,  0.03504104,  0.17504364,  0.71113664,  0.46226028,
          0.682038  ,  0.5079564 ,  0.12735783, -0.19697438, -0.5585122 ],
        [ 0.2762116 ,  0.8439265 ,  0.33712485, -1.2095174 , -0.17419289,
          0.13946502,  0.14711182,  0.4732441 ,  0.68180895,  0.5579827 ],
        [ 0.2343097 ,  0.5049208 ,  0.6808184 ,  0.22736323,  0.14680737,
          0.2668972 , -0.7924594 ,  0.51938015, -0.5769116 , -0.5299431 ],
        [-0.30745247,  0.38900828,  

In [77]:
model.layers[0].weights[0][1]

<tf.Tensor: shape=(49,), dtype=float32, numpy=
array([-0.27706805,  0.25002897, -0.419819  ,  0.59392995,  0.1485502 ,
       -0.12907892,  0.62336   ,  0.3395032 ,  0.20487075, -0.21127184,
        0.4752211 ,  0.01133573, -0.6039726 , -0.03212717, -0.4878635 ,
        0.6270028 ,  0.52504045, -0.18606345, -0.2667562 ,  0.5050743 ,
       -0.01345157, -0.33759317,  0.36013448, -0.18635899, -0.17783159,
        0.38438374,  0.09471858, -0.44952565, -0.45259142, -0.35597506,
        0.3096208 , -0.10727202, -0.473725  , -0.41839957, -0.31727052,
        0.27821097, -0.1781024 ,  0.30790317, -0.39417377,  0.383301  ,
        0.01444338, -0.19953956,  0.077108  ,  0.40223277,  0.35875022,
        0.27404806, -0.24312058, -0.39639348, -0.03478944], dtype=float32)>