In [1]:
import math

import numpy as np

In [2]:
arr1 = np.array([[1, 2, 3], [6, 5, 4]])
arr1

array([[1, 2, 3],
       [6, 5, 4]])

In [3]:
arr1.shape

(2, 3)

In [4]:
arr1.ndim

2

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.reshape((3, 2))

array([[1, 2],
       [3, 6],
       [5, 4]])

In [9]:
arr1[0][0] = 0
arr1

array([[0, 2, 3],
       [6, 5, 4]])

In [10]:
arr1[0, 0]

0

In [11]:
arr2 = np.zeros(shape=(4, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
arr3 = np.ones(shape=(2, 3, 4))
arr3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
arr3[0]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.empty((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.arange(0, 10).reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
np.linspace(0, 2 * np.pi, 100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [26]:
np.sin(np.linspace(0, 2 * np.pi, 200))

array([ 0.00000000e+00,  3.15685498e-02,  6.31056313e-02,  9.45798078e-02,
        1.25959705e-01,  1.57214043e-01,  1.88311666e-01,  2.19221577e-01,
        2.49912962e-01,  2.80355229e-01,  3.10518032e-01,  3.40371303e-01,
        3.69885285e-01,  3.99030558e-01,  4.27778068e-01,  4.56099159e-01,
        4.83965601e-01,  5.11349616e-01,  5.38223906e-01,  5.64561683e-01,
        5.90336692e-01,  6.15523241e-01,  6.40096223e-01,  6.64031143e-01,
        6.87304143e-01,  7.09892022e-01,  7.31772266e-01,  7.52923064e-01,
        7.73323331e-01,  7.92952733e-01,  8.11791702e-01,  8.29821460e-01,
        8.47024034e-01,  8.63382275e-01,  8.78879879e-01,  8.93501396e-01,
        9.07232251e-01,  9.20058757e-01,  9.31968129e-01,  9.42948495e-01,
        9.52988909e-01,  9.62079363e-01,  9.70210796e-01,  9.77375101e-01,
        9.83565137e-01,  9.88774735e-01,  9.92998700e-01,  9.96232822e-01,
        9.98473878e-01,  9.99719634e-01,  9.99968847e-01,  9.99221269e-01,
        9.97477646e-01,  

In [27]:
ar1 = np.arange(0, 9).reshape((3, 3))
ar2 = np.arange(9, 18).reshape((3, 3))

In [30]:
del arr1, arr2, arr3

In [31]:
ar1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
ar2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [34]:
ar1 + ar2

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [35]:
ar1 ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [38]:
ar1 > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [37]:
ar1[ar1 > 5]

array([6, 7, 8])

In [39]:
ar1 @ ar2

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [40]:
ar1 * ar2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [41]:
np.dot(ar1, ar2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [42]:
ar1.sum(axis=0)

array([ 9, 12, 15])

In [43]:
np.exp(ar1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [44]:
np.sqrt(ar2)

array([[3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563]])

In [45]:
np.power(ar1, 1 / 3)

array([[0.        , 1.        , 1.25992105],
       [1.44224957, 1.58740105, 1.70997595],
       [1.81712059, 1.91293118, 2.        ]])

In [47]:
ar1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
np.argsort(ar1, axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [48]:
np.argsort(ar1, axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [53]:
np.where(ar1 < 5)

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))

In [51]:
np.where(ar1 < 5, ar1, ar1 * 10)

array([[ 0,  1,  2],
       [ 3,  4, 50],
       [60, 70, 80]])

In [3]:
ex_ar1 = np.random.normal(15, 5 ** (1 / 2), 50).reshape((5, 10))
ex_ar1

array([[15.21029101, 14.45327944, 15.5347892 , 19.05956609, 14.95339208,
        17.66655773, 17.33004528, 15.75168876, 18.79560041, 18.23600818],
       [16.76728283, 14.63553957, 14.51589027, 17.34070298, 13.33500975,
        12.96169688, 15.39612215, 16.10293572, 17.86656687, 16.87673936],
       [14.5504052 , 18.32509036, 10.6663457 , 14.2041881 , 17.69747412,
        15.15484629, 14.39583467, 15.14363498, 13.26173963, 17.61823163],
       [15.45664759, 17.18086347, 15.58194201, 16.13093568, 15.4610119 ,
        14.90880144, 13.39325348, 13.2667868 , 16.8921439 , 15.28078015],
       [17.07307066, 16.49986675, 13.61557886, 15.09884043, 12.91350431,
        14.54262671, 15.53423563, 14.42467574, 15.79035317, 15.06627115]])

In [13]:
def f(x, y):
    return 10 * x + y


b = np.fromfunction(f, (10, 10))
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [14]:
b[1]

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [15]:
b[:, 1]

array([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])

In [16]:
b[0][0]

0.0

In [17]:
b[0, 0]

0.0

In [18]:
b[:5, 0]

array([ 0., 10., 20., 30., 40.])

In [20]:
for i in b:
    print(i)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
[30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
[40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
[50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]
[60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]
[70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
[80. 81. 82. 83. 84. 85. 86. 87. 88. 89.]
[90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [24]:
print(b.flat[:])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [28]:
b.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [29]:
b.reshape(-1, 1)

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.],
       [24.],
       [25.],
       [26.],
       [27.],
       [28.],
       [29.],
       [30.],
       [31.],
       [32.],
       [33.],
       [34.],
       [35.],
       [36.],
       [37.],
       [38.],
       [39.],
       [40.],
       [41.],
       [42.],
       [43.],
       [44.],
       [45.],
       [46.],
       [47.],
       [48.],
       [49.],
       [50.],
       [51.],
       [52.],
       [53.],
       [54.],
       [55.],
       [56.],
       [57.],
       [58.],
       [59.],
       [60.],
       [61.],
       [62.],
       [63.],
       [64.],
       [65.],
       [66.],
       [67.],
       [68.],
       [69.],
       [70.],
      

In [30]:
np.transpose(b)

array([[ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.],
       [ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.],
       [ 2., 12., 22., 32., 42., 52., 62., 72., 82., 92.],
       [ 3., 13., 23., 33., 43., 53., 63., 73., 83., 93.],
       [ 4., 14., 24., 34., 44., 54., 64., 74., 84., 94.],
       [ 5., 15., 25., 35., 45., 55., 65., 75., 85., 95.],
       [ 6., 16., 26., 36., 46., 56., 66., 76., 86., 96.],
       [ 7., 17., 27., 37., 47., 57., 67., 77., 87., 97.],
       [ 8., 18., 28., 38., 48., 58., 68., 78., 88., 98.],
       [ 9., 19., 29., 39., 49., 59., 69., 79., 89., 99.]])

In [31]:
b.T

array([[ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.],
       [ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.],
       [ 2., 12., 22., 32., 42., 52., 62., 72., 82., 92.],
       [ 3., 13., 23., 33., 43., 53., 63., 73., 83., 93.],
       [ 4., 14., 24., 34., 44., 54., 64., 74., 84., 94.],
       [ 5., 15., 25., 35., 45., 55., 65., 75., 85., 95.],
       [ 6., 16., 26., 36., 46., 56., 66., 76., 86., 96.],
       [ 7., 17., 27., 37., 47., 57., 67., 77., 87., 97.],
       [ 8., 18., 28., 38., 48., 58., 68., 78., 88., 98.],
       [ 9., 19., 29., 39., 49., 59., 69., 79., 89., 99.]])

In [32]:
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [33]:
b.resize((5, 20))

In [34]:
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
        33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
        53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
        73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91., 92.,
        93., 94., 95., 96., 97., 98., 99.]])

In [35]:
a1 = np.random.random((4, 4))
a2 = np.random.random((4, 4))
a3 = np.random.random((4, 4))
a4 = np.random.random((4, 4))

In [36]:
a1

array([[0.89822123, 0.16200335, 0.58361004, 0.73594599],
       [0.20299861, 0.14453533, 0.33332127, 0.74935352],
       [0.79658448, 0.10817381, 0.83174057, 0.18635331],
       [0.77070132, 0.41611153, 0.37899681, 0.96951422]])

In [37]:
a2

array([[0.18752938, 0.21224679, 0.47505777, 0.91532796],
       [0.71321967, 0.32737527, 0.16847434, 0.30730677],
       [0.3710947 , 0.15935927, 0.12229602, 0.78439459],
       [0.70439684, 0.78494169, 0.81444986, 0.50512962]])

In [38]:
a3

array([[0.55727819, 0.18248334, 0.91473434, 0.83657004],
       [0.38231277, 0.21888221, 0.41874973, 0.93940145],
       [0.78848789, 0.89556558, 0.99514798, 0.1073427 ],
       [0.25771922, 0.9165717 , 0.02668184, 0.01861682]])

In [39]:
a4

array([[0.53604032, 0.44187923, 0.1479229 , 0.24530132],
       [0.54592246, 0.88097318, 0.49576139, 0.50455755],
       [0.57041093, 0.41185635, 0.66037075, 0.41843032],
       [0.90237196, 0.12369869, 0.54489277, 0.32257002]])

In [41]:
a5 = a4.reshape((4, 2, 2))
a5

array([[[0.53604032, 0.44187923],
        [0.1479229 , 0.24530132]],

       [[0.54592246, 0.88097318],
        [0.49576139, 0.50455755]],

       [[0.57041093, 0.41185635],
        [0.66037075, 0.41843032]],

       [[0.90237196, 0.12369869],
        [0.54489277, 0.32257002]]])

In [43]:
np.vstack((a1, a2))

array([[0.89822123, 0.16200335, 0.58361004, 0.73594599],
       [0.20299861, 0.14453533, 0.33332127, 0.74935352],
       [0.79658448, 0.10817381, 0.83174057, 0.18635331],
       [0.77070132, 0.41611153, 0.37899681, 0.96951422],
       [0.18752938, 0.21224679, 0.47505777, 0.91532796],
       [0.71321967, 0.32737527, 0.16847434, 0.30730677],
       [0.3710947 , 0.15935927, 0.12229602, 0.78439459],
       [0.70439684, 0.78494169, 0.81444986, 0.50512962]])

In [44]:
np.hstack((a3, a4))

array([[0.55727819, 0.18248334, 0.91473434, 0.83657004, 0.53604032,
        0.44187923, 0.1479229 , 0.24530132],
       [0.38231277, 0.21888221, 0.41874973, 0.93940145, 0.54592246,
        0.88097318, 0.49576139, 0.50455755],
       [0.78848789, 0.89556558, 0.99514798, 0.1073427 , 0.57041093,
        0.41185635, 0.66037075, 0.41843032],
       [0.25771922, 0.9165717 , 0.02668184, 0.01861682, 0.90237196,
        0.12369869, 0.54489277, 0.32257002]])

In [47]:
a5 = np.random.random((1, 2))
a5

array([[0.31303675, 0.2648125 ]])

In [49]:
print(a5[0])

[0.31303675 0.2648125 ]


In [50]:
a5[0][:, np.newaxis]

array([[0.31303675],
       [0.2648125 ]])

In [3]:
np.random.random(2).reshape((1, 2))

array([[0.12846393, 0.39749253]])

In [4]:
a6 = np.random.random(36).reshape((6, 6))
a6

array([[0.94275686, 0.50387285, 0.26622173, 0.55188792, 0.81135373,
        0.57233034],
       [0.97551818, 0.63088733, 0.34941605, 0.23096944, 0.85312886,
        0.22088918],
       [0.01117057, 0.13570776, 0.81318535, 0.77104633, 0.00388107,
        0.08498896],
       [0.6661657 , 0.13620375, 0.2261874 , 0.373317  , 0.37513594,
        0.32965613],
       [0.66365898, 0.17585472, 0.7348024 , 0.03535932, 0.58421487,
        0.18001401],
       [0.34366021, 0.60777849, 0.956079  , 0.16022578, 0.31667321,
        0.07019118]])

In [5]:
np.hsplit(a6, 3)

[array([[0.94275686, 0.50387285],
        [0.97551818, 0.63088733],
        [0.01117057, 0.13570776],
        [0.6661657 , 0.13620375],
        [0.66365898, 0.17585472],
        [0.34366021, 0.60777849]]),
 array([[0.26622173, 0.55188792],
        [0.34941605, 0.23096944],
        [0.81318535, 0.77104633],
        [0.2261874 , 0.373317  ],
        [0.7348024 , 0.03535932],
        [0.956079  , 0.16022578]]),
 array([[0.81135373, 0.57233034],
        [0.85312886, 0.22088918],
        [0.00388107, 0.08498896],
        [0.37513594, 0.32965613],
        [0.58421487, 0.18001401],
        [0.31667321, 0.07019118]])]

In [6]:
np.vsplit(a6, 3)

[array([[0.94275686, 0.50387285, 0.26622173, 0.55188792, 0.81135373,
         0.57233034],
        [0.97551818, 0.63088733, 0.34941605, 0.23096944, 0.85312886,
         0.22088918]]),
 array([[0.01117057, 0.13570776, 0.81318535, 0.77104633, 0.00388107,
         0.08498896],
        [0.6661657 , 0.13620375, 0.2261874 , 0.373317  , 0.37513594,
         0.32965613]]),
 array([[0.66365898, 0.17585472, 0.7348024 , 0.03535932, 0.58421487,
         0.18001401],
        [0.34366021, 0.60777849, 0.956079  , 0.16022578, 0.31667321,
         0.07019118]])]

In [7]:
np.hsplit(a6, 2)

[array([[0.94275686, 0.50387285, 0.26622173],
        [0.97551818, 0.63088733, 0.34941605],
        [0.01117057, 0.13570776, 0.81318535],
        [0.6661657 , 0.13620375, 0.2261874 ],
        [0.66365898, 0.17585472, 0.7348024 ],
        [0.34366021, 0.60777849, 0.956079  ]]),
 array([[0.55188792, 0.81135373, 0.57233034],
        [0.23096944, 0.85312886, 0.22088918],
        [0.77104633, 0.00388107, 0.08498896],
        [0.373317  , 0.37513594, 0.32965613],
        [0.03535932, 0.58421487, 0.18001401],
        [0.16022578, 0.31667321, 0.07019118]])]

In [8]:
np.vsplit(a6, 2)

[array([[0.94275686, 0.50387285, 0.26622173, 0.55188792, 0.81135373,
         0.57233034],
        [0.97551818, 0.63088733, 0.34941605, 0.23096944, 0.85312886,
         0.22088918],
        [0.01117057, 0.13570776, 0.81318535, 0.77104633, 0.00388107,
         0.08498896]]),
 array([[0.6661657 , 0.13620375, 0.2261874 , 0.373317  , 0.37513594,
         0.32965613],
        [0.66365898, 0.17585472, 0.7348024 , 0.03535932, 0.58421487,
         0.18001401],
        [0.34366021, 0.60777849, 0.956079  , 0.16022578, 0.31667321,
         0.07019118]])]

In [11]:
a6

array([[0.94275686, 0.50387285, 0.26622173, 0.55188792, 0.81135373,
        0.57233034],
       [0.97551818, 0.63088733, 0.34941605, 0.23096944, 0.85312886,
        0.22088918],
       [0.01117057, 0.13570776, 0.81318535, 0.77104633, 0.00388107,
        0.08498896],
       [0.6661657 , 0.13620375, 0.2261874 , 0.373317  , 0.37513594,
        0.32965613],
       [0.66365898, 0.17585472, 0.7348024 , 0.03535932, 0.58421487,
        0.18001401],
       [0.34366021, 0.60777849, 0.956079  , 0.16022578, 0.31667321,
        0.07019118]])

In [15]:
np.hsplit(a6, (2, 5))

[array([[0.94275686, 0.50387285],
        [0.97551818, 0.63088733],
        [0.01117057, 0.13570776],
        [0.6661657 , 0.13620375],
        [0.66365898, 0.17585472],
        [0.34366021, 0.60777849]]),
 array([[0.26622173, 0.55188792, 0.81135373],
        [0.34941605, 0.23096944, 0.85312886],
        [0.81318535, 0.77104633, 0.00388107],
        [0.2261874 , 0.373317  , 0.37513594],
        [0.7348024 , 0.03535932, 0.58421487],
        [0.956079  , 0.16022578, 0.31667321]]),
 array([[0.57233034],
        [0.22088918],
        [0.08498896],
        [0.32965613],
        [0.18001401],
        [0.07019118]])]

In [16]:
a7 = np.arange(12)
a7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
b = a7

In [18]:
b is a7

True

In [19]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
b[0] = -250

In [21]:
b

array([-250,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [22]:
a7

array([-250,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [23]:
id(a7)

2199935894608

In [24]:
id(b)

2199935894608

In [25]:
id(a7) == id(b)

True

In [26]:
c = a7.view()

In [27]:
c

array([-250,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [28]:
c[0] = 600

In [29]:
c is a7

False

In [30]:
c

array([600,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [31]:
a7

array([600,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [32]:
b

array([600,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [33]:
id(c)

2199940790864

In [34]:
id(a7)

2199935894608

In [35]:
id(c) == id(a7)

False

In [36]:
d = a7.copy()

In [37]:
d is a7

False

In [38]:
d[0] = 0

In [39]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
a7

array([600,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [41]:
id(d)

2199942364688

In [42]:
id(a7)

2199935894608

In [43]:
id(d) == id(a7)

False

In [15]:
a8 = np.arange(0, 9)
b8 = np.array([10])

In [16]:
a8

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
b8

array([10])

In [18]:
a8 + b8

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [19]:
a9 = np.arange(0, 9).reshape((3, 3))
b9 = np.arange(0, 3)

In [20]:
a9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
b9

array([0, 1, 2])

In [22]:
a9 + b9

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [23]:
a10 = np.array([[1, 2], [3, 4]])


In [24]:
a10.transpose()

array([[1, 3],
       [2, 4]])

In [25]:
np.linalg.inv(a10)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [26]:
np.dot(a10,np.linalg.inv(a10))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [28]:
np.floor(a10@np.linalg.inv(a10))

array([[1., 0.],
       [0., 0.]])

In [29]:
y=np.array([[5],[8]])

In [30]:
np.linalg.solve(a10,y)

array([[-2. ],
       [ 3.5]])

In [31]:
np.linalg.inv(a10)@y

array([[-2. ],
       [ 3.5]])